name: Run the tests of PurBeurre app

on: [push, workflow_dispatch]



jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pg_db:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: p10_db_ci_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PG_PWD }}
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_PASSWORD: ${{ secrets.DB_PG_PWD }}
      DB_NAME: p10_db_ci_test

    steps:
    - name: Checking out code from the repository
      uses: actions/checkout@v2

    - name: Setting up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Django dev server
      run: |
        python manage.py runserver

    - name: Test with unittest
      run: |
        python manage.py test --verbosity 2